#
# Copyright 2024, DornerWorks
#
# SPDX-License-Identifier: BSD-2-Clause
#

[package]
name = "zynqmp_hal"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
tock-registers = "0.9.0"
zynqmp_pac = { path = "../zynqmp_pac"}
eth_phy = { path = "../eth_phy"}
